### ISSUE TITLE
UI|Widok z tablicą wyników

### ISSUE THREAD

**Issue by n0macx** [CC2021-WBL/Project-I#95]
Mode Ranking czy Hall of Fame ?????????

**Comment by RobertS-ki** [comment]
Zaprogramowanie przycisku " Hall of Fame" i jego działania.
Treść przycisku zamiennie: Hall of Fame / Rules. Domyślnie na Initial Screen pokazuję się "Hall of Fame". Po jego wciśnięciu, w oknie "div class="game__mode-rules" ma pojawić się treść z 3ma najlepszymi wynikami Hall of Fame danej kategorii gry oraz danego tryby gry (settings). 
Przycisk na ekranie initial screen:
![obraz](https://user-images.githubusercontent.com/96307488/146911581-59fff3c5-5c1e-4e82-8b8b-a81302227fee.png)
Podmiana diva game__mode-rules na treść Hall of Fame jak nizej:
![obraz](https://user-images.githubusercontent.com/96307488/146914498-b6642ccd-3a3b-4ece-8774-a728a7cffe09.png)

Po wciśnięciu przycisku, pojawia się nowa treść w divie, a treść na przycisku zmienia się na "Rules".
Będzie w sumie 9 różnych Hall of Fame (3 kategorie, 3 poziomy trudności).
